### ISSUE TITLE
migrate to helix-log

### ISSUE THREAD

**Issue by tripodsan** [adobe/openwhisk-loggly-wrapper#35]
this project should use helix-log and be renamed accordingly.

alternatively, we could just use the new `wrap` function that will be added to openwhisk-action-utils: https://github.com/adobe/openwhisk-action-utils/pull/8/commits/62870fabdde0cdaa0a6853a88a384030d8993107

**Comment by tripodsan** [comment]
@trieloff WDYT?

**Comment by trieloff** [comment]
Agree.

**Comment by trieloff** [comment]
What about `helix-openwhisk-log-wrapper` to keep the naming pattern?

**Comment by koraa** [comment]
Hmm, since we're going to move away from loggly, is it worth to migrate this project? We could make it a generic log forwarder, on the other hand I am right now discussing with the id team to implement a runtime level log forwarder…

**Comment by trieloff** [comment]
We can still deprecate this project when the Adobe I/O Runtime team delivers, but that might take a while.

**Comment by koraa** [comment]
Well, we do already have a working logger in helix-log for coralogix; maybe we should forward to that setup instead…
I do not think continuing to use loggly is a good idea in any case…

**Comment by kptdobe** [comment]
What is the status here ? 
I need "project actions" to log things in Coralogix like Helix actions in order to achieve https://github.com/adobe/helix-home/issues/70. Otherwise, I am stuck.
@trieloff @tripodsan @koraa

**Comment by tripodsan** [comment]
i'll look into it tomorrow.

**Comment by tripodsan** [comment]
this is no longer needed as this is handled differently in pipeline.
