### ISSUE TITLE
remove ow parameter magic from loggly wrapper

### ISSUE THREAD

**Issue by tripodsan** [adobe/openwhisk-loggly-wrapper#6]
this _openwhisk-loggly-wrapper_ does more than just wrap loggly, it also moves all uppercase action params to the secrets.

IMO, we should remove all action-parameter functionality and keep it as a "pure" loggly client.

the rest of the logic should move to helix-cli

@trieloff WDYT?

related to https://github.com/adobe/petridish/issues/46

**Comment by tripodsan** [comment]
...or we could move all code to helix-cli. having a own repository/package is not really needed at this point in time...

**Comment by trieloff** [comment]
I'm fine with moving all of it into helix-cli. The wrapper is unlikely to be used outside Helix.

**Comment by tripodsan** [comment]
how about, we keep the original invocation form, but just add a `__ow_logger` param, with a new logger if not present? and in our _hypermedia-pipeline_ create the `action.request`, the `action.logger`, etc ?

eg:

```js
/**
 * Wraps a function with proper logging, before and after.
 * @param fn The openwhisk function to wrap
 * @param params the action params
 * @returns {*} the return value of the action
 */
function wrap(fn, params) {
  if (!params.__ow_logger) {
    params.__ow_logger = defaultlogger(params);
  }
  const logger = params.__ow_logger;
  .
  .
}
```  


@trieloff @kptdobe  WDYT?

**Comment by trieloff** [comment]
+1

**Comment by tripodsan** [comment]
@kptdobe if you are still working on #8, please take over this issue and its PR #9

**Comment by kptdobe** [comment]
ok, I'll take over when done with the rest. Many parallel discussions while I was working on the Global Scope issue, I could not follow...

**Comment by tripodsan** [comment]
also, with moving the wrapper logic to helix-cli, #8 is no longer needed.
